### ISSUE TITLE
Code formatter will trigger wolfram lint(Different Line)

### ISSUE THREAD

**Issue by asukaminato0721** [WolframResearch/codeformatter#3]
```mma
foo[someVery[xxx], someVeryLongFunctionName[xxx, xxx], someVeryLongFunctionName@ xxx]
```

Will be formatted into

```mma
foo[someVery[xxx], someVeryLongFunctionName[xxx, xxx], someVeryLongFunctionName
     @ xxx]
```

then 
![image](https://user-images.githubusercontent.com/30024051/195305789-4cd15684-1965-407c-b731-b3235e8d0849.png)

---

May be can be like this?

```mma
foo[
    someVery[xxx], 
    someVeryLongFunctionName[xxx, xxx], 
    someVeryLongFunctionName @ xxx
]
```

Also, `<|  |>` has this problem.

```mma
<|xxx -> xxx, xxx1 -> xxx, xxx2 -> xxx, xxx3 -> xxx, xxx4 -> xxx, xxx5 -> xxx|>
```

Becomes

```mma
<|xxx -> xxx, xxx1 -> xxx, xxx2 -> xxx, xxx3 -> xxx, xxx4 -> xxx, xxx5
     -> xxx|>
```

![image](https://user-images.githubusercontent.com/30024051/195309276-0f644bab-7e5b-4077-a9e3-3eb1700ff7da.png)

**Comment by bostick** [comment]
CodeFormatter is not good at handling line breaks right now. You can supply a line width of Infinity by doing this:
```
In[4]:= CodeFormat["foo[someVery[xxx], someVeryLongFunctionName[xxx, \
xxx], someVeryLongFunctionName@ xxx]", "LineWidth" -> Infinity]

Out[4]= "foo[someVery[xxx], someVeryLongFunctionName[xxx, xxx], \
someVeryLongFunctionName @ xxx]"
```

and then everything stays on a single line.

Unfortunately, that is also not what you want.

It is hard for the formatter to know what to put on multiple lines (like in your suggestion) or to keep on a single line.

It looks like you are using VSCode from the screenshots.

In VSCode, you can do this in the settings to set the line width:
```
"wolfram.command": [
    "`kernel`",
    "-noinit",
    "-noprompt",
    "-nopaclet",
    "-nostartuppaclets",
    "-noicon",
    "-run",
    "Needs[\"LSPServer`\"];CodeFormatter`$DefaultLineWidth=Infinity;LSPServer`StartServer[]"
]
```

**Comment by asukaminato0721** [comment]
Temporary solved it.

**Comment by HuanNV9** [comment]
Is there any additional setup for that to work?
I just put that piece of code into the default user settings JSON, but it became grey, which means that VSCode doesn't recognize the code.

`"wolfram.command": [
    "`kernel`",
    "-noinit",
    "-noprompt",
    "-nopaclet",
    "-nostartuppaclets",
    "-noicon",
    "-run",
    "Needs[\"LSPServer`\"];CodeFormatter`$DefaultLineWidth=Infinity;LSPServer`StartServer[]"
]`
